export const sdaiFAQ = [
  {
    title: 'What is sDAI?',
    content: (
      <p>
        Savings xDAI allows you to earn the DSR (Dai Savings Rate) directly on Gnosis, you can
        simply deposit your xDAI into Savings xDAI and start earning the Maker DSR rate directly on
        Gnosis
      </p>
    ),
  },
  {
    title: 'Where is the yield coming from?',
    content: (
      <p>
        Savings xDAI is being redirected all Interest from the xDAI Bridge on Ethereum mainnet. The
        bridge has its DAI deposits converted into Savings DAI on mainnet which accrues the DSR. The
        DSR (Dai Savings Rate) is the rate the Maker Protocol pays out to users who deposit into it.
        This yield is generated by the revenue Maker generates on users who mint DAI as well as the
        RWAs it holds.
      </p>
    ),
  },
  {
    title: 'Why is it higher than Maker Dai Savings Rate?',
    content: (
      <p>
        As most DAI in the Gnosis bridge has been moved into Savings DAI on mainnet, as long as
        there are less sDAI on Gnosis than sDAI in the Gnosis xDAI bridge, the interest rate on
        Gnosis should be higher than on mainnet.
      </p>
    ),
  },
  {
    title: 'Why did i get less sDAI than the xDAI I deposited?',
    content: (
      <p>
        sDAI are shares in a pool of xDAI. If more xDAI goes in while the number of shares stays the
        same, the value of each share goes up in value. This is why sDAI costs more than 1 xDAI and
        should keep going up in time
      </p>
    ),
  },
  {
    title: 'Can I use Savings xDAI in DeFi?',
    content: (
      <p>
        Yes. sDAI is an ERC4626 token which is fully compatible with ERC20 standard. This makes it
        perfect for defi integrations. You can currently use it here in Agave as collateral.
      </p>
    ),
  },
] as Array<{ title: string; content: React.ReactNode }>
